---
name: logs-load-test-cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * 1-5'

jobs:
  run-job:
    uses: ./.github/workflows/logs-load-test.yml
    permissions:
      contents: write
    with:
      total_lines: "3000000"
